[cerebrium.deployment]
name = "mtailor-assessment"
python_version = "3.10"
include = ["./*"]
exclude = [".*"]
shell_commands = [""]

[cerebrium.hardware]
cpu = 1
memory = 2.0
compute = "CPU"
gpu_count = 0
provider = "aws"
region = "us-east-1"

[cerebrium.runtime.custom]
port = 8000
dockerfile_path = "./Dockerfile"

[cerebrium.scaling]
min_replicas = 0
max_replicas = 2
cooldown = 1
replica_concurrency = 100